# Generated by Django 2.0.13 on 2019-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.CharField(default='', max_length=500),
        ),
    ]
