# Generated by Django 2.0.13 on 2019-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0002_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(max_length=500),
        ),
    ]
