# Generated by Django 2.0.13 on 2019-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0005_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='About_Me',
        ),
    ]
