# Generated by Django 2.0.13 on 2019-07-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0007_auto_20190703_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
