# Generated by Django 2.0.13 on 2019-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0010_events_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HS', 'Hairstyle'), ('MU', 'Make-Up'), ('TR', 'Travel'), ('SH', 'Shoes'), ('AC', 'Accessoirs'), ('OD', 'Outfit of the Day')], default='OD', max_length=2),
        ),
    ]
