# Generated by Django 2.0.13 on 2019-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0011_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HS', 'Hairstyle'), ('MU', 'Make-Up'), ('SH', 'Shoes'), ('AC', 'Accessoirs'), ('OD', 'Outfit of the Day'), ('EE', 'Everything Else')], default='EE', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
