# Generated by Django 2.0.13 on 2019-08-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionist', '0012_auto_20190801_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='age',
        ),
        migrations.RemoveField(
            model_name='about_me',
            name='favourite_food',
        ),
        migrations.RemoveField(
            model_name='about_me',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='about_me',
            name='name',
        ),
    ]
